name: Build

on:
  pull_request:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  build:
    uses: dt-uibk-workshop/github-workflows/.github/workflows/build-docker-with-helm.yaml@main
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write
    with:
      IMAGE_NAME: ${{ github.repository }}
      HELM_CHART_LOCATION: chart
    secrets:
      TOKEN: ${{ secrets.RENOVATE_DISPATCH_TOKEN }}
