name: PR Commit-Linting

on:
  workflow_call:
  pull_request:

jobs:
  commitlint:
    uses: AndreasDoblander/github-workflows-techvisits/.github/workflows/commit-linting.yaml@main
    permissions:
      contents: read # for checkout
